'''
Bernstein-Vazirani Algorithm

This algorithm solves for s in the Boolean function f(x) = x.s mod 2, where here this reffers to the bit-wise product: x.s = Sum(x_i*s_i). 
Classically this requires n queries to determine s, however using the BV algorithm it can be solved in a single query.
'''

from qiskit import *
from qiskit_aer import AerSimulator
from Oracle import BV_oracle as oracle


n_qubits = 3
qc = QuantumCircuit(n_qubits+1,n_qubits) # Initialises a quantum circuit with an n_qubit input register, an ancilla qubit for the oracle output and a register of classical bits corresponding to the input register to measure into.
oracle = oracle(n_qubits)

qc.x(n_qubits) # Initalises the ancilla qubit in the |1> state.
qc.h(range(n_qubits + 1)) # Performs a Hadamard gate operation on all qubits (including ancilla). This initialises the circuit ready for the oracle.

#Apply the oracle function:
qc = oracle.f(qc)

qc.h(range(n_qubits+1)) # Apply Hadamard gate to all register qubits and ancilla
qc.measure(range(n_qubits), range(n_qubits)) # Measure the register qubits states

# Now simulate this circuit running 1024 times on a quantum computer:
simulator = AerSimulator()
job = simulator.run(qc, shots=1024)
result = job.result()
counts = result.get_counts()

most_common = max(counts, key=counts.get)
times = str(counts[most_common])
print("The algorithm returned the result " + most_common + " in " + times + " simulations, out of 1024")
print("The binary number generated by the oracle was " + oracle.s)

