'''
Grover's Search Algorithm
'''

from qiskit import *
from qiskit_aer import AerSimulator
from Oracle import Grover_oracle as oracle
from collections import Counter
import numpy as np
from qiskit.circuit.library import ZGate
from qiskit import transpile

n_qubits = 3
qc = QuantumCircuit(n_qubits,n_qubits) 
oracle = oracle(n_qubits)
qc.h(range(n_qubits)) 

#Apply the oracle function, marking one of the states:
qc = oracle.f(qc)


def inversion(qc, n_qubits=n_qubits):
	qc.h(range(n_qubits))
	qc.x(range(n_qubits)) 
	multi_controlled_z = ZGate().control(n_qubits-1)
	qc.append(multi_controlled_z, range(n_qubits))
	qc.x(range(n_qubits)) 
	qc.h(range(n_qubits)) 
	return qc

qc = inversion(qc)
qc.measure(range(n_qubits), range(n_qubits))
simulator = AerSimulator()
qc_transpiled = transpile(qc, simulator)
job = simulator.run(qc_transpiled, shots=1024)
result = job.result()
counts = result.get_counts()

most_common = max(counts, key=counts.get)
times = str(counts[most_common])
most_common = most_common[::-1]
print("The algorithm returned the result " + most_common + " in " + times + " simulations, out of 1024")
print("The binary number generated by the oracle was " + oracle.mark)

